name: 'Switch userns remap'
description: 'Switch userns remap settings to Docker of current runner'
inputs:
  enable:
    description: 'enable userns remap'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: switch settings
      run: |
        if test "${ENABLE}" = "true"; then
          sudo cat /etc/docker/daemon.json | jq '.+{"userns-remap":"runner:docker"}' > tmp.json
        else
          sudo cat /etc/docker/daemon.json | jq 'del(."'"userns-remap"'")' > tmp.json
        fi
        sudo bash -c 'cat tmp.json > /etc/docker/daemon.json'
        rm tmp.json
        sudo systemctl restart docker || sudo journalctl -xeu docker.service
      env:
        ENABLE: ${{ inputs.enable }}
      shell: bash
