name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  snif:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: snif
        run: |
          id
          ls -l /etc/subuid /etc/subgid
          cat /etc/subuid
          cat /etc/subgid
          echo ---
          sudo ls -l /etc/docker/
          sudo cat /etc/docker/daemon.json
          echo ---
          docker info
          echo ---
          sudo systemctl status docker
        shell: bash

      - name: setup
        run: |
          sudo cat /etc/docker/daemon.json | jq '.+{"userns-remap":"runner:docker"}' > tmp.json
          sudo mv tmp.json /etc/docker/daemon.json 
          sudo cat /etc/docker/daemon.json
          sudo systemctl restart docker || sudo journalctl -xeu docker.service
          echo ---
          docker info
          echo ---
          sudo systemctl status docker
        shell: bash