name: test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  snif:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: snif
        run: |
          id
          ls -l /etc/subuid /etc/subgid
          cat /etc/subuid
          cat /etc/subgid
          echo ---
          sudo ls -l /etc/docker/
          sudo cat /etc/docker/daemon.json
          echo ---
          docker info
          echo ---
          docker image ls -a
          echo ---
          sudo systemctl status docker
        shell: bash

      - name: setup
        run: |
          sudo cat /etc/docker/daemon.json | jq '.+{"userns-remap":"default"}' > tmp.json
          sudo mv tmp.json /etc/docker/daemon.json 
          sudo cat /etc/docker/daemon.json
          sudo systemctl restart docker || sudo journalctl -xeu docker.service
          echo ---
          docker info
          echo ---
          sudo systemctl status docker
        shell: bash

      - name: default
        run: |
          grep dockremap /etc/passwd
          grep dockremap /etc/group
          echo ---
          cat /etc/subuid
          cat /etc/subgid
        shell: bash

      - name: run
        run: |
          mkdir chk
          chmod a+rwx chk
          docker run -u guest -v "${PWD}:/mnt" --rm alpine:latest \
            ash -c 'id && cat /proc/self/uid_map && echo "hey taishou" > /mnt/chk/hey.txt'
          ls -l chk
          cat chk/hey.txt
        shell: bash